declare type DataTarget = 'Product' | 'User' | 'UserAndProduct' | 'Department' | 'General' | 'ProductExternal';

declare type EditorUITarget =
    | 'SaveProject'
    | 'AddToBasket'
    | 'FreeTarget'
    | 'ViewControls'
    | 'BatchArea'
    | 'TabArea'
    | 'Pages'
    | 'TextField'
    | 'PreviewButton'
    | 'TopRightArea'
    | 'BottomRightArea'
    | 'MainControlsArea'
    | 'BottomLeftArea'
    | 'LeftTopSidebarGallery'
    | 'LeftBottomSidebarGallery'
    | 'LeftTopSidebarBackground'
    | 'LeftBottomSidebarBackground'
    | 'LeftTopSidebarLayout'
    | 'LeftBottomSidebarLayout'
    | 'LeftTopSidebarClipArt'
    | 'LeftBottomSidebarClipArt'
    | 'LeftTopSidebarDrawing'
    | 'LeftBottomSidebarDrawing'
    | 'OutsideContainer'
    | 'CustomTab'
    | 'FieldsTab'
    | 'ToolsTab';

declare type EditorEvents =
    | 'BeforeCanvasChange'
    | 'BeforeOutputTypeChange'
    | 'BeforeStockChange'
    | 'CanvasChanged'
    | 'OutputTypeChanged'
    | 'StockChanged'
    | 'TogglePreview'
    | 'BeforeTogglePreview'
    | 'ToggleFullScreen'
    | 'BeforeToggleFullScreen'
    | 'AddToBasket'
    | 'AddToBasketPreSave'
    | 'SaveAsProject'
    | 'SaveAsProjectPreSave'
    | 'SaveEmbeddedPreSave'
    | 'BeforePageChange'
    | 'PageChanged'
    | 'BeforeLayoutChange'
    | 'LayoutChanged'
    | 'BeforePageDelete'
    | 'PageDeleted'
    | 'BeforePageAdd'
    | 'PageAdded'
    | 'BeforePageMove'
    | 'PageMoved'
    | 'OpenPreview'
    | 'BeforeOpenPreview'
    | 'ClosePreview'
    | 'BeforeClosePreview'
    | 'MappingSaved'
    | 'BatchDataSaved'
    | 'Editor.Loaded';

declare type FieldEvents =
    | 'BeforeInsert'
    | 'BeforeAdd'
    | 'Add'
    | 'MoveAndSize'
    | 'BeforeZIndex'
    | 'ZIndex'
    | 'BeforeZIndexPage'
    | 'ZIndexPage'
    | 'BeforeDelete'
    | 'Delete'
    | 'Selection'
    | 'TextFieldEditStart'
    | 'TextFieldEditEnd'
    | 'TextFieldEditKeyPressed'
    | 'FieldTextFlowFinished'
    | 'ImageChanged';

declare type MEvents = EditorEvents | FieldEvents;